apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config

commonLabels:
  app.kubernetes.io/component: controller
  app.kubernetes.io/version: v0.0.1

images:
- name: controller
  newName: docker.io/jeewangue/postgres-indb-operator
  newTag: v0.0.1
