# permissions for end users to edit pgdatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pgdatabase-editor-role
rules:
- apiGroups:
  - postgres.jeewangue.com
  resources:
  - pgdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.jeewangue.com
  resources:
  - pgdatabases/status
  verbs:
  - get
