# permissions for end users to view pgdatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pgdatabase-viewer-role
rules:
- apiGroups:
  - postgres.jeewangue.com
  resources:
  - pgdatabases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgres.jeewangue.com
  resources:
  - pgdatabases/status
  verbs:
  - get
