# permissions for end users to edit pghostcredentials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pghostcredential-editor-role
rules:
- apiGroups:
  - postgres.jeewangue.com
  resources:
  - pghostcredentials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.jeewangue.com
  resources:
  - pghostcredentials/status
  verbs:
  - get
