# permissions for end users to view pghostcredentials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pghostcredential-viewer-role
rules:
- apiGroups:
  - postgres.jeewangue.com
  resources:
  - pghostcredentials
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgres.jeewangue.com
  resources:
  - pghostcredentials/status
  verbs:
  - get
