apiVersion: postgres.jeewangue.com/v1alpha1
kind: PgUser
metadata:
  name: user1
spec:
  name:
    value: user1
  password:
    value: user1
  accessSpecs:
    - hostCredential: pghostcredential-sample
      database: test1
      permission: "readwrite"
    - hostCredential: pghostcredential-sample
      database: test2
      permission: "readwrite"
---
apiVersion: postgres.jeewangue.com/v1alpha1
kind: PgUser
metadata:
  name: user2
spec:
  name:
    value: user2
  password:
    value: user2
  accessSpecs:
    - hostCredential: pghostcredential-sample
      database: test1
      permission: "readonly"
    - hostCredential: pghostcredential-sample
      database: test2
      permission: "readonly"
    - hostCredential: pghostcredential-sample2
      database: test3
      permission: "readwrite"

