apiVersion: postgres.jeewangue.com/v1alpha1
kind: PgUser
metadata:
  name: pguser-sample
spec:
  name:
    value: sample2
  password:
    value: sample
  accessSpecs:
    - hostCredential: pghostcredential-sample
      database: sample11
      permission: "readwrite"
---
apiVersion: postgres.jeewangue.com/v1alpha1
kind: PgUser
metadata:
  name: pguser-sample2
spec:
  name:
    value: sample3
  password:
    value: sample
  accessSpecs:
    - hostCredential: pghostcredential-sample
      database: sample11
      permission: "readonly"

